---
- hosts: all
  remote_user: vagrant
  become: yes
  become_method: sudo
  tasks:
    - name: Insert New Line
      blockinfile:
        path: /etc/hosts
        insertafter: "192.168.200.20"
        content: |
           192.168.200.20  librenms   librenms.example.com

#    - name: Restart SNMPD Service
#      action: service name=snmpd state=restarted

